#!/usr/bin/env python3

# This script faulty did's within documents inside s3:storage.cardstack.com/card-space
# did's generated by CardSpace short code was incorrectly "cs" rather than "c"

import json
import os

import boto3
from python_did_resolver.main import EncodeOptions, encode_did, get_resolver, su


def get_all_file_names_local(local_dir):
    return os.listdir(local_dir)


def extract_uid_local(file_name):
    "removes json extension"
    return file_name.split(".")[0]


def edit_file_local(local_dir, file_name):
    with open(f"{local_dir}/{file_name}", "r") as f:
        uid = extract_uid_local(file_name)
        o = json.load(f)
        old_did = o["data"]["attributes"]['did']
        encode_options: EncodeOptions = {
            "version": 1,
            "type": "CardSpace",
            "uniqueId": uid,
        }
        did = encode_did(encode_options)
        if did == old_did:
            raise Exception("New did same as old did")
        o["data"]["attributes"]["did"] = did
    with open(f"{local_dir}/{file_name}", "w") as f:
        json.dump(o, f, separators=(',', ':'))


if __name__ == "__main__":
    local_dir = "local-card-space"
    file_names = get_all_file_names_local(local_dir)
    for n in file_names:
        print(n)
        edit_file_local(local_dir, n)
    # edit_file_local(local_dir, "12LLwAK2fsp3pHv1ZCddTP.json")
    # bucket = 'storage.cardstack.com'
    # file_keys = get_all_file_names(bucket, 'card-space/')
    # for f in file_keys:
    #     print(f)
    #     edit_file(bucket, f)
    # edit_file(bucket, "foo/12LLwAK2fsp3pHv1ZCddTP.json")
