name: Deploy subgraph extractor
description: Deploy subgraph extractor using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: '0.4.0'

runs:
  using: composite
  steps:
    - name: Install apt packages including waypoint
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}

    - name: Deploy subgraph extractor
      run: waypoint up -app=cardpay-subg-ext -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: '1'
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'
