name: Deploy subgraph extractor
description: Deploy subgraph extractor using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.8.1"

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v1

    - name: Install dependencies
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}
        yarn add hcl2-parser @actions/core -W --prefer-offline

    - name: Deploy subgraph extractor
      run: waypoint up -app=cardpay-subg-ext -prune-retain=0 -plain
      shell: bash

    - name: Prune dangling resources
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "cardpay-subg-ext"
