name: Notify deploy status with Discord
description: Send a Discord message when to inform about deployment status

inputs:
  app:
    description: Name of the app
    required: true
  environment:
    description: Deployment environment
    required: true
  discord_token:
    description: Authentication token for Discord bot
    required: true
  discord_channel:
    description: ID of the Discord channel to send the notification
    required: true

runs:
  using: composite
  steps:
    - name: Print job status
      run: |
        echo github.action_status=${{ github.action_status }}
        echo job.status=${{ job.status }}
      shell: bash

    - name: Send success notification to Discord
      if: ${{ github.action_status == 'Success' && job.status == 'success'}}
      uses: ./.github/actions/discord-message
      with:
        token: ${{ inputs.discord_channel }}
        channel: ${{ inputs.discord_channel }}
        message: |
          :checkered_flag: **${{ inputs.app }}** [${{ github.ref }}] has been successfully deployed to *${{ inputs.environment }}*
          :arrow_forward: Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Fetch stopped reason and logs
      id: debug
      if: ${{ github.action_status == 'Failure' || job.status == 'failure' }}
      uses: ./.github/actions/fetch-stopped-ecs-task
      with:
        app: ${{ inputs.app }}

    - name: Send failure notification to Discord
      if: ${{ ( github.action_status == 'Failure' || job.status == 'failure' ) && steps.debug.outputs.has_stopped_task == 'true' }}
      uses: ./.github/actions/discord-message
      with:
        token: ${{ inputs.discord_channel }}
        channel: ${{ inputs.discord_channel }}
        message: |
          :warning: **${{ inputs.app }}** [${{ github.ref }}] has failed to deploy to *${{ inputs.environment }}*
          :arrow_forward: Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Tasks stopped for reason:
          ```
          ${{ steps.debug.outputs.stopped_reason }}
          ```
          View the latest logs at ${{ steps.debug.outputs.logs_url }}

    - name: Send failure notification to Discord
      if: ${{ ( github.action_status == 'Failure' || job.status == 'failure' ) && steps.debug.outputs.has_stopped_task == 'false' }}
      uses: ./.github/actions/discord-message
      with:
        token: ${{ inputs.discord_channel }}
        channel: ${{ inputs.discord_channel }}
        message: |
          :warning: **${{ inputs.app }}** [${{ github.ref }}] has failed to deploy to *${{ inputs.environment }}*
          :arrow_forward: Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
