[project]
name = "cardpay-reward-api"
version = "0.1.0"
description = ""
authors = [
    {name = "tintinthong", email = "justin.thong@cardstack.com"},
]
license-expression = "MIT"
dependencies = [
    "fastapi[all]>=0.75.1",
    "SQLAlchemy>=1.4.35",
    "psycopg2>=2.9.3",
    "pyarrow>=7.0.0",
    "cloudpathlib[s3]>=0.7.1",
    "hexbytes>=0.2.2",
    "json-stream>=1.3.0",
    "fastapi-utils>=0.2.1",
    "python-dotenv>=0.20.0",
    "eth-abi>=2.1.1",
    "uvicorn>=0.15.0",
]
requires-python = ">=3.9"

[project.urls]
Homepage = ""
[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
main = "uvicorn cardpay_reward_api.main:app"
dev = "uvicorn cardpay_reward_api.main:app --reload"
test = "python -m cardpay_reward_api.main"
