[project]
name = "cardpay-reward-api"
version = "0.1.0"
description = ""
authors = [
    {name = "tintinthong", email = "justin.thong@cardstack.com"},
]
license-expression = "MIT"
dependencies = [
    "fastapi[all]>=0.75.1",
    "SQLAlchemy>=1.4.35",
    "psycopg2>=2.9.3",
    "hexbytes>=0.2.2",
    "uvicorn>=0.15.0",
    "sentry-sdk>=1.5.12",
    "web3>=5.29.2"]
requires-python = ">=3.9"

[project.urls]
Homepage = ""

[project.optional-dependencies]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.2",
    "mock>=4.0.3",
    "black>=22.1.0",
    "flake8>=4.0.1",
]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
main = "python -m cardpay_reward_api.main"
dev = "uvicorn cardpay_reward_api.main:app --reload"
