name: 'Find PR number'
description: 'Find a PR number for a PR that is targeting main, given the branch name'
branding:
  icon: 'message-circle'
  color: 'purple'
inputs:
  branch:
    description: 'Branch associated with PR'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
