name: Deploy an Ember PR preview
description: Deploy a preview of an Ember PR

inputs:
  environment:
    description: Deployment environment
    required: true
  package:
    description: Name of the package to deploy
    required: true
    default: web-client

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Set up node_modules cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
          packages/firebase-functions/*/functions/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Install dependencies
      shell: bash
      run: yarn --prefer-offline
    - name: Set PR branch name
      shell: bash
      run: echo "RAW_PR_BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
    - name: Convert branch name to subdomain-compatible form
      shell: bash
      run: echo "PR_BRANCH_NAME=`echo ${RAW_PR_BRANCH_NAME} | tr _ - | tr '[:upper:]' '[:lower:]' | sed -e 's/-$//' | sed -e 's/[^a-z0-9\-]//g'`" >> $GITHUB_ENV
    - name: Deploy preview
      shell: bash
      run: yarn deploy:${{ inputs.package }}:preview-${{ inputs.environment }}

    - name: Store preview host
      shell: bash
      run: echo "PREVIEW_HOST=https://$PR_BRANCH_NAME.$S3_PREVIEW_BUCKET_NAME/" >> $GITHUB_ENV
    - name: add check with link to preview deployment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPOSITORY/statuses/$HEAD_SHA \
          -d '{"context":"Preview ${{ inputs.package }} ${{ inputs.environment }}","description":"${{ inputs.environment }} deployment of this branch","target_url":"'"$PREVIEW_HOST"'","state":"success"}'
