name: Waypoint Deploy
description: Deploy waypoint app

inputs:
  app:
    description: Name of the app, specified in waypoint.hcl
    required: true
  retain:
    description: Number of deployments to retain
    required: false
    default: "1"
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.11.3"
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4

    - uses: lucasmelin/setup-waypoint@v1
      with:
        version: ${{ inputs.waypoint_version }}

    - name: Install dependencies
      shell: bash
      run: |
        yarn --prefer-offline --frozen-lockfile

    - name: Deploy app
      run: waypoint up -app=${{ inputs.app }} -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: "1"

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: ./.github/actions/discord-notification-deploy
      with:
        app: ${{ inputs.app }}
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
        is_ecs: "true"
