name: Deploy SSR web
description: Deploy a FastBoot server serving a stripped down web-client

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.8.1"
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v1

    - name: Install dependencies
      shell: bash
      run: yarn --prefer-offline

    - name: Build
      run: SSR_WEB_ENVIRONMENT=${{ inputs.environment }} yarn build:ssr-web:${{ inputs.environment }}
      shell: bash

    - name: Move dist content
      run: mv dist deployment/
      shell: bash
      working-directory: packages/ssr-web

    - name: Deploy ssr-web
      uses: ./.github/actions/waypoint-deploy
      with:
        app: ssr-web
        environment: ${{ inputs.environment }}
        discord_webhook: ${{ inputs.discord_webhook }}
