name: Deploy cardie
description: Deploy cardie using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.4.0"

runs:
  using: composite
  steps:
    - name: Install apt packages including waypoint
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}

    - uses: volta-cli/action@v1

    - run: yarn --prefer-offline
      shell: bash

    - name: Deploy cardie
      run: waypoint up --app=cardie -prune-retain=0 -plain
      shell: bash

    - name: Prune dangling resources
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "cardie"
