name: Deploy Reward Api
description: Deploy FastApi Server

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.8.1"
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v1

    - name: Install dependencies
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}
        yarn add hcl2-parser @actions/core -W --prefer-offline

    - name: Deploy reward api
      run: waypoint up -app=reward-api -plain
      shell: bash

    - uses: ./.github/actions/waypoint-ecs-failsafe
      with:
        app: reward-api

    - name: Prune dangling resources
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: reward-api
        retain: "1"

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: ./.github/actions/discord-notification-deploy
      with:
        app: reward-api
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
        is_ecs: "true"
