name: Setup node_modules Cache

inputs:
  yarn_lock_md5:
    description: content hash for the yarn.lock file
    required: true

runs:
  using: composite
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up node_modules cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          node_modules
          packages/*/node_modules
          packages/ember-shared/*/node_modules
          packages/firebase-functions/*/functions/node_modules
        key: ${{ runner.os }}-yarn-node-modules-${{ inputs.yarn_lock_md5 }}
        restore-keys: |
          ${{ runner.os }}-yarn-node-modules-
