name: Deploy web-client PR preview
description: Deploy a preview of a web-client PR

inputs:
  environment:
    description: Deployment environment
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v4

    - uses: ./.github/actions/setup-node-modules-cache
      with:
        yarn_lock_md5: ${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      shell: bash
      run: yarn --prefer-offline --frozen-lockfile

    - name: Set PR branch name
      shell: bash
      run: echo "RAW_PR_BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

    - name: Convert branch name to subdomain-compatible form
      shell: bash
      run: echo "PR_BRANCH_NAME=`echo ${RAW_PR_BRANCH_NAME} | tr _ - | tr '[:upper:]' '[:lower:]' | sed -e 's/-$//' | sed -e 's/[^a-z0-9\-]//g'`" >> $GITHUB_ENV

    - name: Deploy preview
      shell: bash
      run: yarn deploy:web-client:preview-${{ inputs.environment }}

    - name: Store preview host
      shell: bash
      run: echo "PREVIEW_HOST=https://$PR_BRANCH_NAME.$S3_PREVIEW_BUCKET_NAME/" >> $GITHUB_ENV

    - name: add check with link to preview deployment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPOSITORY/statuses/$HEAD_SHA \
          -d '{"context":"Preview web-client ${{ inputs.environment }}","description":"${{ inputs.environment }} deployment of this branch","target_url":"'"$PREVIEW_HOST"'","state":"success"}'
