[project]
name = "cardpay-reward-indexer"
version = "0.1.0"
description = ""
authors = [
    {name = "tintinthong", email = "justin.thong@cardstack.com"},
]
dependencies = [
    "schedule>=1.1.0",
    "pydantic>=1.9.1",
    "cloudpathlib[s3]>=0.9.0",
    "pyarrow>=8.0.0",
    "eth-abi>=2.1.1",
    "requests>=2.28.0",
    "hexbytes>=0.2.2",
    "sqlalchemy>=1.4.37",
    "psycopg2>=2.9.3",
    "eth-hash[pycryptodome]>=0.3.2",
    "sentry-sdk>=1.5.12",
    "web3>=5.29.2",
]
requires-python = ">=3.9"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.2",
    "isort>=5.10.1",
    "black>=22.3.0",
    "flake8>=4.0.1",
]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
main = "python -m cardpay_reward_indexer.main"
check_sync = "python -m scripts.check_sync"
