name: Deploy hub
description: Deploy hub using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.8.1"
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v1

    - run: yarn --prefer-offline
      shell: bash

    - name: Install dependencies
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}

    - name: Webpack build
      run: yarn build
      shell: bash
      working-directory: packages/hub

    - name: Deploy server
      run: waypoint up --app=hub -plain
      shell: bash

    - uses: ./.github/actions/waypoint-ecs-failsafe
      with:
        app: "hub"

    - name: Prune dangling resources [hub]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub"
        retain: "1"

    - name: Deploy worker
      run: waypoint up --app=hub-worker -prune-retain=0 -plain
      shell: bash

    - name: Prune dangling resources [hub-worker]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub-worker"

    - name: Deploy event handler
      run: waypoint up --app=hub-event-listener -prune-retain=0 -plain
      shell: bash

    - name: Prune dangling resources [hub-event-listener]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub-event-listener"

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: ./.github/actions/discord-notification-deploy
      with:
        app: hub
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
        is_ecs: "true"
