name: Deploy hub
description: Deploy hub using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.4.0"

runs:
  using: composite
  steps:
    - name: Install apt packages including waypoint
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}

    - uses: volta-cli/action@v1

    - run: yarn --prefer-offline
      shell: bash

    - name: Webpack build
      run: yarn build
      shell: bash
      working-directory: packages/hub

    - name: Deploy server
      run: waypoint up --app=hub -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: "1"
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: "1"

    - name: Prune dangling resources [hub]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub"
        retain: "1"

    - name: Deploy worker
      run: waypoint up --app=hub-worker -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: "1"
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: "1"

    - name: Prune dangling resources [hub-worker]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub-worker"

    - name: Deploy bot
      run: waypoint up --app=hub-bot -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: "1"
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: "1"

    - name: Prune dangling resources [hub-bot]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub-bot"

    - name: Deploy event handler
      run: waypoint up --app=hub-event-listener -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: "1"
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: "1"

    - name: Prune dangling resources [hub-event-listener]
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "hub-event-listener"
