name: Deploy hub
description: Deploy hub using waypoint

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: '0.4.0'

runs:
  using: composite
  steps:
    - name: Install apt packages including waypoint
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}

    - uses: volta-cli/action@v1

    - run: yarn --prefer-offline
      shell: bash

    - name: Deploy server
      run: waypoint up --app=hub -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: '1'
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'

    - name: Deploy worker
      run: waypoint up --app=hub-worker -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: '1'
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'

    - name: Deploy bot
      run: waypoint up --app=hub-bot -prune-retain=0 -plain
      shell: bash
      env:
        WAYPOINT_SERVER_TLS: '1'
        WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'
