import MediaRegistryDiscrepanciesDiscrepancyCardController from '../card';

export default class MediaRegistryDiscrepanciesDiscrepancyCardIndexController extends MediaRegistryDiscrepanciesDiscrepancyCardController {}
