name: Deploy reward scheduler
description: Deploy the reward program scheduler

inputs:
  waypoint_version:
    description: Waypoint version to use
    required: false
    default: "0.4.0"
  environment:
    description: Deployment environment
    required: true

runs:
  using: composite
  steps:
    - uses: volta-cli/action@v1

    - name: Install apt packages including waypoint
      shell: bash
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint=${{ inputs.waypoint_version }}
        yarn add js-hcl-parser -W --prefer-offline

    - name: Deploy reward scheduler
      run: waypoint up -app=reward-scheduler -prune-retain=0 -plain
      shell: bash

    - name: Prune dangling resources
      uses: ./.github/actions/waypoint-prune-dangling-resources
      with:
        app: "reward-scheduler"
