name: Init
description: Setup common dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: "package.json"

    - uses: cardstack/gh-actions/setup-yarn-volta@main

    - uses: ./.github/actions/setup-node-modules-cache
      with:
        yarn_lock_md5: ${{ hashFiles('yarn.lock') }}

    - run: yarn --prefer-offline --frozen-lockfile
      shell: bash
