name: Manual Deploy [safe-tools-client]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/firebase-functions/*/functions/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Deploy web-client
        uses: ./.github/actions/deploy-safe-tools-client
        with:
          environment: ${{ github.event.inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
