name: Manual Deploy [safe-tools-client]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up env
        env:
          INPUT_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          if [ "$INPUT_ENVIRONMENT" = "production" ]; then
            echo "HUB_URL=https://hub.cardstack.com" >> $GITHUB_ENV
          elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
            echo "HUB_URL=https://hub-staging.stack.cards" >> $GITHUB_ENV
          else
            echo "unrecognized environment"
            exit 1;
          fi

      - name: Deploy safe-tools-client
        uses: ./.github/actions/deploy-safe-tools-client
        with:
          environment: ${{ github.event.inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
        env:
          SENTRY_DSN: ${{ secrets.SAFE_TOOLS_CLIENT_SENTRY_DSN }}
