name: Manual publish

on:
  workflow_dispatch:
    inputs:
      bump:
        description: |
          Increment version(s) by explicit version or_ semver keyword,
          'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', 'from-git', or 'from-package'
        required: true
        default: patch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: volta-cli/action@v4

      - name: Set up node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/firebase-functions/*/functions/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Prepare dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > $HOME/.npmrc
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Publish
        run: |
          npx lerna publish ${{ github.event.inputs.bump }} --force-publish "*" --yes --no-verify-access
