name: Manual Deploy [web-client]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: production

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up env
        env:
          INPUT_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          if [ "$INPUT_ENVIRONMENT" = "production" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/web-client" >> $GITHUB_ENV
            echo "HUB_URL=https://hub.cardstack.com" >> $GITHUB_ENV
          elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/web-client" >> $GITHUB_ENV
            echo "HUB_URL=https://hub-staging.stack.cards" >> $GITHUB_ENV
          else
            echo "unrecognized environment"
            exit 1;
          fi

      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy web-client
        uses: ./.github/actions/deploy-web-client
        env:
          SENTRY_DSN: ${{ secrets.WEB_CLIENT_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.WEB_CLIENT_SENTRY_AUTH_TOKEN }}
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Send success notification to Discord
        if: ${{ success() }}
        uses: ./.github/actions/discord-message
        with:
          token: ${{ secrets.DISCORD_TOKEN }}
          channel: ${{ secrets.DISCORD_CHANNEL }}
          message: |
            :checkered_flag: **web-client** [${{ github.ref }}] has been successfully deployed to *${{ github.event.inputs.environment }}*
            :arrow_forward: Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send failure notification to Discord
        if: ${{ failure() }}
        uses: ./.github/actions/discord-message
        with:
          token: ${{ secrets.DISCORD_TOKEN }}
          channel: ${{ secrets.DISCORD_CHANNEL }}
          message: |
            :warning: **web-client** [${{ github.ref }}] has failed to deploy to *${{ github.event.inputs.environment }}*
            :arrow_forward: Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
