name: CI [cardpay-subgraph]

on:
  pull_request:
    paths:
      - "packages/cardpay-sdk/**"
      - "packages/cardpay-subgraph/**"
      - "packages/eslint-config/**"
      - ".github/workflows/pr-cardpay-subgraph.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - name: Set up node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/firebase-functions/*/functions/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn --prefer-offline

      - run: yarn codegen:subgraph-sokol && yarn build:subgraph

      - run: yarn codegen:subgraph-xdai && yarn build:subgraph
