name: CI [cardpay-reward-indexer]

on:
  pull_request:
    paths:
      - "packages/cardpay-reward-indexer/**"
      - ".github/workflows/pr-cardpay-reward-indexer.yml"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cardpay-reward-indexer
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pdm
          pdm install -d
          pdm add setuptools
      - name: Test with pytest
        env:
          DB_STRING: "sqlite:///./test.db"
        run: |
          pdm run -s pytest tests
