name: CI [cardpay-sdk]

on:
  pull_request:
    paths:
      - "packages/cardpay-sdk/**"
      - "packages/eslint-config/**"
      - ".github/workflows/pr-cardpay-sdk.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - run: yarn test:cardpay-sdk
