name: CI [ember-shared]

on:
  pull_request:
    paths:
      - "packages/ember-shared/**"
      - 'packages/eslint-config/**'
      - ".github/workflows/pr-ember-shared.yml"
      - "package.json"
      - "yarn.lock"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - uses: ./.github/actions/setup-node-modules-cache
        with:
          yarn_lock_md5: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Run tests
        run: yarn test:ember-shared
