name: CI [ember-shared]

on:
  pull_request:
    paths:
      - "packages/ember-shared/**"
      - "packages/eslint-config/**"
      - ".github/workflows/pr-ember-shared.yml"
      - "package.json"
      - "yarn.lock"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - name: Run tests
        run: yarn test:ember-shared
