name: CI [python-linter-check]

on:
  pull_request:
    paths:
      - "**.py"
      - '.github/workflows/pr-python-linter-check.yml'

jobs:
  test:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: flake8
        uses: py-actions/flake8@v2
      - name: black
        uses: psf/black@stable
      - name: isort
        uses: jamescurtin/isort-action@master
