name: CI [python-did-resolver]

on:
  pull_request:
    paths:
      - "packages/python-did-resolver/**"
      - "packages/did-resolver/**"
      - "packages/test-support/**"
      - "packages/eslint-config/**"
      - ".github/workflows/pr-python-did-resolver.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/python-did-resolver
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: volta-cli/action@v4
      - uses: ./.github/actions/setup-node-modules-cache
        with:
          yarn_lock_md5: ${{ hashFiles('yarn.lock') }}

      - run: yarn add -W ts-node --prefer-offline

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pdm
          pdm config python.use_venv false
          pdm install -d

      - name: Test with pytest
        run: |
          pdm run -s pytest tests
