name: CI [waypoint]

on:
  pull_request:
    paths:
      - ".github/workflows/pr-waypoint.yml"
      - "scripts/verify-waypoint-secrets.ts"
      - "package.json"
      - "waypoint.hcl"
      - "waypoint.prod.hcl"
      - "yarn.lock"

permissions:
  contents: read
  id-token: write

jobs:
  check:
    name: Check Secret Access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - uses: ./.github/actions/setup-node-modules-cache
        with:
          yarn_lock_md5: ${{ hashFiles('yarn.lock') }}

      - run: yarn --prefer-offline --frozen-lockfile

      - name: Configure staging AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::680542703984:role/waypoint
          aws-region: us-east-1

      - name: Check access to secrets specified in waypoint.hcl
        uses: ./.github/actions/check-secrets
        with:
          waypoint_config_file: waypoint.hcl

      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::120317779495:role/waypoint
          aws-region: us-east-1

      - name: Check access to secrets specified in waypoint.prod.hcl
        uses: ./.github/actions/check-secrets
        with:
          waypoint_config_file: waypoint.prod.hcl
