name: CI [wc-provider]

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/wc-provider/**'
      - 'packages/eslint-config/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --prefer-offline
      - name: WC Provider Tests
        run: yarn test
        working-directory: packages/wc-provider
