name: CI [wc-provider]

on:
  pull_request:
    paths:
      - "packages/wc-provider/**"
      - "packages/eslint-config/**"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init

      - name: WC Provider Tests
        run: yarn test
        working-directory: packages/wc-provider
