name: CI [wc-provider]

on:
  pull_request:
    paths:
      - "packages/wc-provider/**"
      - "packages/eslint-config/**"
      - "package.json"
      - "yarn.lock"

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - uses: ./.github/actions/setup-node-modules-cache
        with:
          yarn_lock_md5: ${{ hashFiles('yarn.lock') }}

      - run: yarn --prefer-offline --frozen-lockfile

      - name: WC Provider Tests
        run: yarn test
        working-directory: packages/wc-provider
