name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # only run tests for pushes to master as part of the deploy Action, where we set is_deploying to true.
    # vars specified using `with:` are automatically all-caps and prefixed with INPUT
    if: github.ref != 'refs/heads/master' || INPUT_IS_DEPLOYING 
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Set up build cache (yarn)
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-${{ hashFiles('/**/yarn.lock') }}
    - name: Set up build cache (eslint)
      uses: actions/cache@v1
      with:
        path: .eslintcache
        key: ${{ runner.os }}-eslint
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start prereqs
      run: |
        docker network create cardstack
        docker run -d --rm --network cardstack -p 5444:5432 --name postgres cardstack/pg-test
        docker run -d --rm --network cardstack -p 8838:80 --name git-http cardstack/git-http-server;
    - name: yarn install
      run: yarn install
    - name: Linting
      run: |
        yarn lint:deps
        yarn lint:js
    - name: wait for db
      run: node packages/pgsearch/node-tests/wait-for-db.js
      env:
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres

    - name: Node tests
      run: yarn node-tests
      env:
        CI: true
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres
    - name: Ember tests
      run: yarn ember-tests
      env:
        CI: true
        PGHOST: localhost
        PGPORT: 5444
        PGUSER: postgres
